datastores:
  secoda:
    existing_secret: ""
    admin_password: "" # We suggest using `openssl rand -hex 20 | cut -c 1-16` to fill this value.
    secret_key: "" # You must use `uuidgen | tr '[:upper:]' '[:lower:]'` to fill this value.
    private_key: "" # openssl genrsa -out secoda.private.pem 2048 && echo "Copy the following:" && cat secoda.private.pem | base64
    public_key: "" # openssl rsa -in secoda.private.pem -pubout > secoda.public.pem && echo "Copy the following:" && cat secoda.public.pem | base64
    db_host: "" # NOTE: If using `cloudSqlAuthProxy`, this value should be set to `localhost`. Otherwise, this should be similar to `rds.amazonrds.com` or an ip address. 
    db_password: "" # this should be alphanumeric, or it may break connection strings.

ingress:
  enabled: true
  annotations: []
  tls:
    - secretName: lb
  hosts:
    - host: on-premise.secoda.co # Replace me.
      paths:
        - path: /*
          pathType: Prefix

cloudSqlAuthProxy:
  enabled: false # Only supported on GCP.
  databaseName: secoda-gke # Replace me with the correct GCP database name, i.e. "secoda-gke".