# Default values for secoda.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

services:
  api:
    image:
      registry: ""
      name: "on-premise-api"
      pullPolicy: ""
      tag: ""
    command: []
    args: []
    env: []
    ports:
      - containerPort: 5007
    resources:
      requests:
        memory: 2048Mi
        cpu: 1024m
      limits:
        memory: 4096Mi
        cpu: 1024m
    readinessProbe:
      tcpSocket:
        port: 5007
    securityContext: {}
  
  frontend:
    image:
      registry: ""
      name: "on-premise-frontend"
      pullPolicy: ""
      tag: ""
    args: []
    env: []
    ports:
      - name: https
        containerPort: 443
      - name: http
        containerPort: 80
    resources:
      requests:
        memory: 2048Mi
        cpu: 512m
    livenessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 30
      timeoutSeconds: 5
    readinessProbe: {}
    securityContext: {}

  auth:
    image:
      registry: ""
      name: "on-premise-auth"
      pullPolicy: ""
      tag: ""
    env:
      - name: KC_DB_USERNAME
        value: keycloak
      - name: KC_DB
        value: postgres
      - name: KEYCLOAK_ADMIN
        value: admin
    ports:
      - containerPort: 8080
      - containerPort: 8443
    args: 
      - start --auto-build --db=postgres --http-relative-path /auth --hostname-strict false --proxy edge --spi-login-protocol-openid-connect-legacy-logout-redirect-uri=true --import-realm
    resources:
      requests:
        memory: 2048Mi
        cpu: 512m
      limits:
        memory: 2048Mi
        cpu: 512m
    livenessProbe: {}
    readinessProbe:
      httpGet:
        path: /auth/realms/secoda/.well-known/openid-configuration
        port: 8080
      initialDelaySeconds: 90
      timeoutSeconds: 5
      periodSeconds: 10
    securityContext: {}

  redis:
    image:
      registry: "docker.io"
      name: "redis"
      pullPolicy: ""
      tag: "6.2"
    env: []
    ports:
      - containerPort: 6379
    command: ["redis-server"]
    resources:
      requests:
        memory: 1024Mi
        cpu: 256m
      limits:
        memory: 1024Mi
        cpu: 256m
    livenessProbe: {}
    readinessProbe:
      tcpSocket:
        port: 6379
    securityContext: {}

global:
  image:
    registry: "secoda"
    pullPolicy: Always
    tag: "4"
  env: []
  resources: {}
  securityContext: {}
    # allowPrivilegeEscalation: false

persistence:
  enabled: false

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

service:
  type: NodePort

nodeSelector: {}
tolerations: []
affinity: {}
dnsConfig: {}
annotations: {}
