repos:
  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.11.0
    hooks:
      - id: helm-docs
        args:
          [--chart-search-root=charts/secoda]
  - repo: local
    hooks:
      - id: bump
        name: bump
        entry: .pre-commit/bump.sh
        language: script
        types: [bash]
        pass_filenames: false
