{{- if not .Values.datastores.secoda.existing_secret }}
apiVersion: v1
kind: Secret
metadata:
  name: secoda-keycloak
type: Opaque
stringData:
  APISERVICE_DATABASE_CONNECTION: postgresql://keycloak:{{ .Values.datastores.secoda.db_password }}@{{ .Values.datastores.secoda.db_host }}:5432/secoda
  PRIVATE_KEY: {{ .Values.datastores.secoda.private_key }}
  PUBLIC_KEY: {{ .Values.datastores.secoda.public_key }}
  KC_DB_URL: jdbc:postgresql://{{ .Values.datastores.secoda.db_host }}/keycloak
  KC_DB_PASSWORD: {{ .Values.datastores.secoda.db_password }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.datastores.secoda.admin_password }}
  KEYCLOAK_SECRET: {{ .Values.datastores.secoda.secret_key }}
{{- end -}}