apiVersion: v1
kind: Service
metadata:
  name: {{ include "secoda.fullname" . }}
  labels:
    {{- include "secoda.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "secoda.selectorLabels" . | nindent 4 }}
