name: Release

on:
  push:
    branches:
      - main
    paths:
      - "charts/secoda/**"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: install helm
        run: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      - name: run helm
        working-directory: charts/secoda
        run: |
          helm template -f examples/predefined-secrets.yaml . > 1.yaml
      - name: test predefined
        uses: docker://ghcr.io/yannh/kubeconform:master
        with:
          entrypoint: "/kubeconform"
          args: "-summary -output json charts/secoda/1.yaml"
  release:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: commit docs changes
        run: |
          new_version=$(./bump.sh)
          git commit -am "ci: version bump $new_version"
          git push
      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.1
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.3.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"