name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: chrisdickinson/setup-yq@latest
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.1'
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      # - name: update chart version
      #   run: |
      #     yq w -i Chart.yaml version "4.$GITHUB_RUN_NUMBER.0"
      #     git commit -am "[skip ci] Automated version update"
      # - name: install helm-docs
      #   run: GO111MODULE=on go get github.com/norwoodj/helm-docs/cmd/helm-docs
      # - name: run helm-docs
      #   run: helm-docs --template-files=README.md.gotmpl
      # - name: commit docs changes
      #   run: | 
      #     git commit -am "[ci skip] docs update"
      #     git push
      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.1
      - name: move files
        run: | 
          mkdir charts
          cp *.yaml charts/
          cp -rf templates charts/
          cp .helmignore charts/
          cp README.md charts/
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.3.0
        with:
          charts_dir: charts
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
