name: Release

on:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: install helm
        run: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      - name: run helm
        working-directory: charts/secoda
        run: |
          helm template -f examples/predefined-secrets.yaml . > 1.yaml
      - name: test predefined
        uses: docker://ghcr.io/yannh/kubeconform:master
        with:
          entrypoint: "/kubeconform"
          args: "-summary -output json charts/secoda/1.yaml"
  release:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - uses: chrisdickinson/setup-yq@latest
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: "1.16.1"
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      # - name: update chart version
      #   run: |
      #    yq w -i charts/secoda/Chart.yaml version "4.$GITHUB_RUN_NUMBER.0"
      #     git commit -am "[skip ci] Automated version update"
      # - name: install helm-docs
      #   run: GO111MODULE=on go get github.com/norwoodj/helm-docs/cmd/helm-docs
      # - name: run helm-docs
      #   run: helm-docs --template-files=README.md.gotmpl
      #   working-directory: charts/secoda
      # - name: commit docs changes
      #   run: |
      #     git commit -am "[ci skip] docs update"
      #     git push
      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.1
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.3.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
