name: Validate

on:
  push:

jobs:
  secoda_validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: install helm
        run: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      - name: run helm
        run: |
          helm template -f examples/predefined-secrets.yaml . > 1.yaml
      - name: test predefined
        uses: docker://ghcr.io/yannh/kubeconform:master
        with:
          entrypoint: '/kubeconform'
          args: "-summary -output json 1.yaml"