name: Validate

on:
  push:
    paths:
      - charts/secoda/*

jobs:
  secoda_validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: install helm
        run: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      - name: run helm
        working-directory: charts/secoda
        run: |
          helm template -f examples/predefined-secrets.yaml . > charts/secoda/1.yaml
      - name: test predefined
        uses: docker://ghcr.io/yannh/kubeconform:master
        with:
          entrypoint: '/kubeconform'
          args: "-summary -output json charts/secoda/1.yaml"